---
- name: Add Mongo debian repo key
  apt_key: keyserver='hkp://keyserver.ubuntu.com:80' id=7F0CEB10 state=present
  sudo: yes
- name: Install Mongo Debian repo
  apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present
  sudo: yes
- name: Install Mongo shell
  apt: update_cache=yes name=mongodb-org-shell
  sudo: yes
- name: Install Mongo tools
  apt: update_cache=yes name=mongodb-org-tools
  sudo: yes