---
- name: Add Mongo debian repo key
  apt_key: keyserver='hkp://keyserver.ubuntu.com:80' id=7F0CEB10 state=present
  sudo: yes
- name: Install Mongo Debian repo
  apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present
  sudo: yes
- name: Install Mongo shell
  apt: update_cache=yes name=mongodb-org-shell
  sudo: yes
- name: Install Mongo tools
  apt: update_cache=yes name=mongodb-org-tools
  sudo: yes

- name: Create directory
  file: state=directory owner=ansible group=ansible path={{ mongo_workspace }}
  sudo: yes

- name: Remove accommodation file on server
  file: state=absent path={{ mongo_workspace }}accommodation.json
- name: Push accommodation file on server
  copy: src=../files/accommodation.json dest={{ mongo_workspace }}accommodation.json
- name: Remove accommodations
  command: mongo --host {{ mongo_host }} --port {{ mongo_port }} -u {{ mongo_user }} -p {{ mongo_password }} --eval "db.accommodations.remove({})" {{ mongo_database }}
- name: Import accommodations
  command: mongoimport --host {{ mongo_host }}:{{ mongo_port }} -u {{ mongo_user }} -p {{ mongo_password }} --db {{ mongo_database }} --collection accommodations --jsonArray --file {{ mongo_workspace }}accommodation.json
- name: Remove accommodation file on server
  file: state=absent path={{ mongo_workspace }}accommodation.json

- name: Remove gifts file on server
  file: state=absent path={{ mongo_workspace }}gift.json
- name: Push gift file on server
  copy: src=../files/gift.json dest={{ mongo_workspace }}gift.json
- name: Remove gifts
  command: mongo --host {{ mongo_host }} --port {{ mongo_port }} -u {{ mongo_user }} -p {{ mongo_password }} --eval "db.gifts.remove({})" {{ mongo_database }}
- name: Import gifts
  command: mongoimport --host {{ mongo_host }}:{{ mongo_port }} -u {{ mongo_user }} -p {{ mongo_password }} --db {{ mongo_database }} --collection gifts --jsonArray --file {{ mongo_workspace }}gift.json
- name: Remove gift file on server
  file: state=absent path={{ mongo_workspace }}gift.json

- name: Remove password file on server
  file: state=absent path={{ mongo_workspace }}password.json
- name: Push password file on server
  copy: src=../files/password.json dest={{ mongo_workspace }}password.json
- name: Remove passwords
  command: mongo --host {{ mongo_host }} --port {{ mongo_port }} -u {{ mongo_user }} -p {{ mongo_password }} --eval "db.passwords.remove({})" {{ mongo_database }}
- name: Import passwords
  command: mongoimport --host {{ mongo_host }}:{{ mongo_port }} -u {{ mongo_user }} -p {{ mongo_password }} --db {{ mongo_database }} --collection passwords --jsonArray --file {{ mongo_workspace }}password.json
- name: Remove password file on server
  file: state=absent path={{ mongo_workspace }}password.json
