---
- name: Install NodeJS
  apt: name=nodejs
  sudo: yes
- name: Link nodejs bin to /usr/bin/node
  file: state=link src=/usr/bin/nodejs path=/usr/bin/node
  sudo: yes
- name: Install npm
  apt: name=npm
  sudo: yes
- name: Copy npmrc to root directory
  copy: src=../files/npmrc dest=/home/ansible/.npmrc owner=ansible group=ansible
- name: Create checkout directory
  file: state=directory owner=ansible group=ansible path={{ angular_folder }}
  sudo: yes
- name: Checkout git repo
  git: repo=git://github.com/francois-travais/wedding-angular.git
       dest={{ angular_folder }}
       accept_hostkey=yes
- name: Install node_modules
  shell: chdir={{ angular_folder }} npm install
- name: Verify that npm install installed bower components
  stat: path={{ angular_folder }}/app/bower_components
  register: st
- fail: msg="Npm install failed"
  when: st.stat.isdir is not defined or not st.stat.isdir
- name: Remove existing files
  shell: rm -rf /var/www/html/*
  sudo: yes
- name: Stop Apache
  service: name=apache2 state=stopped
  sudo: yes
- name: Copy sources to /var/www/html
  shell: cp -r {{ angular_folder }}app/* /var/www/html/
  sudo: yes
- name: Adjust ownership and permissions
  file: state=directory path=/var/www/html/ recurse=yes mode='u=rwx,g=r,o=r' owner=www-data group=www-data
  sudo: yes
- name: Start Apache
  service: name=apache2 state=started
  sudo: yes