---
- name: Update packages
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes
- name: Install git
  apt: name=git
  sudo: yes
- name: Install apache
  apt: name=apache2-bin
  apt: name=apache2
  sudo: yes
- name: Stop apache
  service: name=apache2 state=stopped
  sudo: yes
- name: Disable default Apache sites
  shell: a2dissite '*' || echo -n ''
  sudo: yes