---
- name: Update packages
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes
- name: Install git
  apt: name=git
  sudo: yes
- name: Install apache
  apt: name=apache2
  sudo: yes
- name: Stop apache
  service: name=apache2 state=stopped
  sudo: yes
- name: Disable default Apache sites
  shell: a2dissite '*' || echo -n ''
  notify: reload apache
  sudo: yes

- name: Copy Angular apache site
  template: src=../templates/wedding-angular.conf.j2 dest=/etc/apache2/sites-available/wedding-angular.conf owner=root group=root mode=644
  sudo: yes
- name: Enable Angular Apache site
  shell: a2ensite wedding-angular
  sudo: yes
  notify: reload apache

- name: Copy REST apache site
  template: src=../templates/wedding-rest.conf.j2 dest=/etc/apache2/sites-available/wedding-rest.conf owner=root group=root mode=644
  sudo: yes
- name: Enable REST Apache site
  shell: a2ensite wedding-rest
  sudo: yes
  notify: reload apache

- name: Disable default Apache configurations
  shell: a2disconf '*' || echo -n ''
  notify: reload apache
  sudo: yes
- name: Enable default Apache logging conf
  command: a2enconf other-vhosts-access-log
  notify: reload apache
  sudo: yes

- name: Copy Apache security conf
  copy: src=../files/security.conf dest=/etc/apache2/conf-available/security.conf mode=644 owner=root group=root
  sudo: yes
- name: Enable Apache security conf
  command: a2enconf security
  notify: reload apache
  sudo: yes

- name: Copy Apache charset conf
  copy: src=../files/charset.conf dest=/etc/apache2/conf-available/charset.conf mode=644 owner=root group=root
  sudo: yes
- name: Enable Apache charset conf
  command: a2enconf charset
  notify: reload apache
  sudo: yes